-- ========================================================
-- PET SHOP - BANHO E TOSA (Schema PostgreSQL / Supabase)
-- ========================================================
-- Este script cria ou atualiza a tabela necessária para o Pet Shop.
-- No Supabase: vá em "SQL Editor" -> "New query" -> cole e clique em "RUN".

CREATE TABLE IF NOT EXISTS fichas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_cachorro TEXT NOT NULL,
  nome_tutor TEXT NOT NULL,
  telefone_tutor TEXT DEFAULT '',
  data_atendimento TEXT NOT NULL,
  horario_atendimento TEXT NOT NULL DEFAULT '08:00',
  pacote TEXT NOT NULL DEFAULT 'Não',
  servicos TEXT NOT NULL,
  perfume TEXT NOT NULL DEFAULT 'Não',
  forma_entrega TEXT NOT NULL DEFAULT 'tutor',
  endereco_busca TEXT DEFAULT '',
  valor NUMERIC(10,2) DEFAULT 0.00,
  observacoes TEXT DEFAULT '',
  status TEXT NOT NULL DEFAULT 'aguardando',
  data_criacao TIMESTAMPTZ DEFAULT TIMEZONE('America/Sao_Paulo', NOW()),
  data_conclusao TIMESTAMPTZ DEFAULT NULL
);

-- Migrações seguras caso a tabela já exista de versão anterior
DO $$
BEGIN
  ALTER TABLE public.fichas ADD COLUMN IF NOT EXISTS telefone_tutor TEXT DEFAULT '';
  ALTER TABLE public.fichas ADD COLUMN IF NOT EXISTS forma_entrega TEXT NOT NULL DEFAULT 'tutor';
  ALTER TABLE public.fichas ADD COLUMN IF NOT EXISTS endereco_busca TEXT DEFAULT '';
  ALTER TABLE public.fichas ADD COLUMN IF NOT EXISTS valor NUMERIC(10,2) DEFAULT 0.00;

  UPDATE public.fichas
  SET forma_entrega = 'tutor'
  WHERE forma_entrega IS NULL OR forma_entrega = '';
END $$;

-- Índices para consultas rápidas
CREATE INDEX IF NOT EXISTS idx_fichas_data_status ON fichas (data_atendimento, status);
CREATE INDEX IF NOT EXISTS idx_fichas_status ON fichas (status);

-- Desativar RLS para permitir leitura e escrita pela API do Pet Shop
ALTER TABLE fichas ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'fichas'
      AND policyname = 'Acesso total publico para o Pet Shop'
  ) THEN
    CREATE POLICY "Acesso total publico para o Pet Shop" ON public.fichas
      FOR ALL
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;
